@startuml

Client -> Server++: ""GET /cat""
    Server -> CatFactApi++: ""GET /fact""
    return ""{ "fact": "some fact", ...}""
    Server -> CatImagesApi++: ""GET /v1/images/search""
    return ""[{ "url": "some url", ...}]""
return ""{ "fact": "some fact", "image_url": "some url" }""

@enduml