@startuml
actor Client
participant Server
participant Collector
participant CatFactApi
participant CatImagesApi

Client -> Server++: ""GET /cat""
    Server -> CatFactApi++: ""GET /fact""
    return ""{ "fact": "Cats are lazy.", ...}""
    Server -> CatImagesApi++: ""GET /v1/images/search""
    return ""[{ "url": "http://catpics.com/8e1bf1f9...", ...}]""
return ""{""\n""  "fact": "Cats are lazy.",""\n""  "image_url": "http://catpics.com/8e1bf1f9..."""\n""}""
== At some point later ==
note over Server
    Periodically, or when enough requests have been
    handled, a batch of spans will be sent to our
    Collector.
end note 
Server -> Collector: ""POST /api/traces""
return ""OK""

@enduml